// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"ws/internal/biz"
	"ws/internal/conf"
	"ws/internal/data"
	"ws/internal/interfaces"
	"ws/internal/server"
	"ws/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer, logger)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	chatRepo := data.NewUserRepo(dataData, logger)
	chatUseCase := biz.NewChatUseCase(chatRepo, logger)
	serviceChatUseCase := service.NewChatUseCase(chatUseCase)
	interfacesChatUseCase := interfaces.NewChatUseCase(serviceChatUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, interfacesChatUseCase, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
